version: 1
disable_existing_loggers: no

formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  error:
    format: "%(asctime)s - %(name)s - %(levelname)s <PID %(process)d:%(processName)s> %(name)s.%(funcName)s(): %(message)s"

handlers:
#  info_file_handler:
#    class: logging.handlers.RotatingFileHandler
#    level: INFO
#    formatter: standard
#    filename: ../logs/info.log
#    maxBytes: 10485760 # 10MB
#    backupCount: 20
#    encoding: utf8
#
#  warn_file_handler:
#    class: logging.handlers.RotatingFileHandler
#    level: WARN
#    formatter: standard
#    filename: ../logs/warn.log
#    maxBytes: 10485760 # 10MB
#    backupCount: 20
#    encoding: utf8
#
  error_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: error
    filename: ../logs/errors.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8
#
#  critical_file_handler:
#    class: logging.handlers.RotatingFileHandler
#    level: CRITICAL
#    formatter: standard
#    filename: ../logs/critical.log
#    maxBytes: 10485760 # 10MB
#    backupCount: 20
#    encoding: utf8
#
#  debug_file_handler:
#    class: logging.handlers.RotatingFileHandler
#    level: DEBUG
#    formatter: standard
#    filename: ../logs/debug.log
#    maxBytes: 10485760 # 10MB
#    backupCount: 20
#    encoding: utf8

  root_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: standard
    filename: ../logs/logs.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard
    stream: ext://sys.stdout

#  error_console:
#    class: logging.StreamHandler
#    level: ERROR
#    formatter: error
#    stream: ext://sys.stderr

  fares_etl_log_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: standard
    filename: ../logs/fares_etl.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8


  msd_schedule_etl_log_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: standard
    filename: ../logs/msd_schedule_etl.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

  lfa_schedule_etl_log_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: standard
    filename: ../logs/lfa_schedule_etl.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

  scraper_job_log_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: standard
    filename: ../logs/scraper_job.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

  dds_job_log_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: standard
    filename: ../logs/dds_job.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8
root:
  level: DEBUG
  handlers: [console, root_file_handler]
  propagate: yes

loggers:
  main:
    level: DEBUG
    handlers: [console, error_file_handler]
    propagate: no
  fares_etl:
    level: DEBUG
    handlers: [fares_etl_log_file_handler, error_file_handler, console]
    propagate: yes
  msd_schedule_etl:
    level: DEBUG
    handlers: [msd_schedule_etl_log_file_handler, error_file_handler, console]
    propagate: yes
  scraper_job:
    level: DEBUG
    handlers: [scraper_job_log_file_handler, error_file_handler, console]
    propagate: yes
  lfa_schedule_etl:
    level: DEBUG
    handlers: [lfa_schedule_etl_log_file_handler, error_file_handler, console]
    propagate: yes
  data_processing_etl:
    level: DEBUG
    handlers: [dds_job_log_file_handler, error_file_handler, console]
    propagate: yes