version: 0.0
os: linux
files:
  - source: /
    destination: /opt/arev/temporary-dir
    overwrite: true
permissions:
  - object: /opt/arev/temporary-dir
    owner: ec2-user
    group: ec2-user
hooks:
  BeforeInstall:
    - location: /.aws/scripts/1_before_install.sh
      timeout: 40
      runas: root
  AfterInstall:
    - location: /.aws/scripts/2_after_install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: /.aws/scripts/stop_server.sh
      timeout: 30
      runas: root
  ApplicationStart:
    - location: /.aws/scripts/start_server.sh
      timeout: 60
      runas: root
file_exists_behavior: OVERWRITE